#spring:
#  application:
#    name: nacos-provider
#  cloud:
#    nacos:
#      discovery:
##        enabled: true
#        server-addr: 127.0.0.1:8848
##        server-addr: 120.78.189.213:8848/
#server:
#  port: 8082
#
#name: ShaoJie
#
## 端口检查 健康检查
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"